src/Entity/Person.php
<?php

namespace App\Entity;

use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 */
class Person
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $gender;

    /**
     * @ORM\OneToMany(targetEntity=TvShow::class, mappedBy="directedBy")
     */
    private $directedTvShows;

    /**
     * @ORM\ManyToMany(targetEntity=Character::class, mappedBy="actors")
     */
    private $characters;

    public function __construct()
    {
        $this->directedTvShows = new ArrayCollection();
        $this->characters = new ArrayCollection();
    }

    public function getFullName()
    {
        return $this->firstName . " " . $this->lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection|TvShow[]
     */
    public function getDirectedTvShows(): Collection
    {
        return $this->directedTvShows;
    }

    public function addDirectedTvShow(TvShow $directedTvShow): self
    {
        if (!$this->directedTvShows->contains($directedTvShow)) {
            $this->directedTvShows[] = $directedTvShow;
            $directedTvShow->setDirectedBy($this);
        }

        return $this;
    }

    public function removeDirectedTvShow(TvShow $directedTvShow): self
    {
        if ($this->directedTvShows->contains($directedTvShow)) {
            $this->directedTvShows->removeElement($directedTvShow);
            // set the owning side to null (unless already changed)
            if ($directedTvShow->getDirectedBy() === $this) {
                $directedTvShow->setDirectedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Character[]
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): self
    {
        if (!$this->characters->contains($character)) {
            $this->characters[] = $character;
            $character->addActor($this);
        }

        return $this;
    }

    public function removeCharacter(Character $character): self
    {
        if ($this->characters->contains($character)) {
            $this->characters->removeElement($character);
            $character->removeActor($this);
        }

        return $this;
    }
}

src/Entity/TvShow.php
<?php

namespace App\Entity;

use App\Repository\TvShowRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TvShowRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class TvShow
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"tvshow:list", "tvshow:read"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"tvshow:list", "tvshow:read"})
     *
     * @Assert\NotBlank
     * @Assert\Length(max=255, maxMessage="Cette valeur est trop longue (maximum {{ limit }} caractères)")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"tvshow:read"})
     */
    private $synopsis;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups({"tvshow:read"})
     * 
     * @Assert\Type("\DateTime")
     */
    private $releaseDate;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="tvShow", orphanRemoval=true)
     */
    private $seasons;

    /**
     * @ORM\OneToMany(targetEntity=Character::class, mappedBy="tvShow", orphanRemoval=true)
     */
    private $characters;

    /**
     * @ORM\ManyToOne(targetEntity=Person::class, inversedBy="directedTvShows")
     */
    private $directedBy;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="tvShows")
     * 
     * @Groups({"tvshow:read"})
     */
    private $categories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     * @Groups({"tvshow:read"})
     */
    private $slug;

    /**
     * @ORM\Column(type="float", nullable=true)
     * 
     * @Groups({"tvshow:read"})
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * 
     * @Groups({"tvshow:read"})
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * 
     * @Groups({"tvshow:read"})
     */
    private $createdAt;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->characters = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function onPersist()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }

    /**
     * @ORM\PreUpdate
     */
    public function onUpdate()
    {
        $this->updatedAt = new \DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->releaseDate;
    }

    public function setReleaseDate(?\DateTimeInterface $releaseDate): self
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setTvShow($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->contains($season)) {
            $this->seasons->removeElement($season);
            // set the owning side to null (unless already changed)
            if ($season->getTvShow() === $this) {
                $season->setTvShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Character[]
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): self
    {
        if (!$this->characters->contains($character)) {
            $this->characters[] = $character;
            $character->setTvShow($this);
        }

        return $this;
    }

    public function removeCharacter(Character $character): self
    {
        if ($this->characters->contains($character)) {
            $this->characters->removeElement($character);
            // set the owning side to null (unless already changed)
            if ($character->getTvShow() === $this) {
                $character->setTvShow(null);
            }
        }

        return $this;
    }

    public function getDirectedBy(): ?Person
    {
        return $this->directedBy;
    }

    public function setDirectedBy(?Person $directedBy): self
    {
        $this->directedBy = $directedBy;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/TvShowType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Person;
use App\Entity\TvShow;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class TvShowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        
        $builder->add(
            "synopsis",
            TextareaType::class,
            [
                "label" => "Synopsis",
                "required" => false,
                "attr" => [
                    "rows" => 5
                ]
            ]
        );
        
        $builder->add(
            "releaseDate",
            DateType::class,
            [
                "label" => "Date de première diffusion",
                "required" => false,
                "widget" => "single_text"
            ]
        );

        $builder->add(
            "categories",
            EntityType::class,
            [
                "class" => Category::class,
                "choice_label" => "label",
                "multiple" => true,
                "expanded" => true,
                "attr" => [
                    "class" => "compact-select-list"
                ]
            ]
        );

        $builder->add(
            "directedBy",
            EntityType::class,
            [
                "class" => Person::class,
                "choice_label" => function (Person $person) {
                    return $person->getFullName();
                },
                "required" => false
            ]
        );

        // https://symfony.com/doc/current/best_practices.html#add-form-buttons-in-templates
        /*
        $builder->add(
            "submit",
            SubmitType::class,
            [
                "label" => "Ajouter / modifier"
            ]
        );
        */

        // on demande au formulaire de rajouter une "réaction" un listener
        // lorsque l'evenement "PRE_SET_DATA" aura lieu, on executera la fonction anonyme suivante
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA, 
            function (FormEvent $event) {

                // l'evenement de type FormEvent contient la donnée manipulée par le formulaire
                // la mathode getData() de l'evenement me permet de récupérer la donnée
                // puisque je suis dans un formulaire qui gère des TvShow
                // getData va me renvoyer le TvShow géré par ce formulaire.
                // (le tvShow que l'on a injecté dans ce formulaire lors de sa création dans le controller avec le createForm(FormType::class, $data))
                /** @var TvShow $tvShow */
                $tvShow = $event->getData();

                // l'evenement contient également le formulaire
                $form = $event->getForm();

                // je crée le chmaps title au moment où le formulaire recoit l'objet
                // qu'il doit manipuler
                // si c'est un tvShow existant (qui à un ID) alors le champs sera
                // disabled
                $form->add(
                    "title",
                    TextType::class,
                    [
                        "label" => "Titre de la série",
                        "disabled" => !empty($tvShow->getId())
                    ]
                );
            }
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TvShow::class,
        ]);
    }
}

src/Controller/TvShowController.php
<?php

namespace App\Controller;

use App\Entity\TvShow;
use App\Form\TvShowType;
use App\Repository\TvShowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tv-show")
 */
class TvShowController extends AbstractController
{
    /**
     * @Route("/list", name="tv_show_list")
     */
    public function list(Request $request)
    {
        $search = $request->query->get('search');

        /** @var TvShowRepository $repository */
        $repository = $this->getDoctrine()->getRepository(TvShow::class);
        $tvShows = $repository->findByTitle($search);
        
        return $this->render(
            'tv_show/list.html.twig',
            [
                "tvShows" => $tvShows
            ]
        );
    }

    /**
     * @Route("/{id}", name="tv_show_view", requirements={"id"="\d+"})
     */
    public function view($id)
    {
        /** @var TvShowRepository $repository */
        $repository = $this->getDoctrine()->getRepository(TvShow::class);
        $tvShow = $repository->findWithCollections($id);

        return $this->render(
            'tv_show/view.html.twig',
             [
                 "tvShow" => $tvShow
             ]
        );
    }
    
}

templates/tv_show/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h2 class="mb-5">Ajouter une série</h2>

{# 
{{ form(tvShowForm) }} <form> <input ...> </form>
#}

{# https://symfony.com/doc/current/form/form_customization.html#form-functions-and-variables-reference #}


{{ form_start(tvShowForm) }} {# <form method=""post"> #}
    
    {# form_widget(tvShowForm) permet d'afficher tout les champs du formulaire d'un coup #}

    <div class="row">
        <div class="col-sm-6">
            {{ form_row(tvShowForm.title) }}
            {{ form_row(tvShowForm.releaseDate) }}
            {{ form_row(tvShowForm.directedBy) }}
            {{ form_row(tvShowForm.categories) }}
        </div>
        <div class="col-sm-6">
            {{ form_row(tvShowForm.synopsis) }}
        </div>
    </div>
    

    <input type="submit" value="Ajouter" class="btn btn-primary">
{{ form_end(tvShowForm) }} {# </form> #}

{% endblock %}

templates/tv_show/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="d-flex flex-row justify-content-between mb-5">
    <h2>Séries</h2>
    <div>
        {% if is_granted('ROLE_TVSHOW_ADMIN') %}
            <a href="{{ path('tv_show_add') }}" class="btn btn-primary">Ajouter</a>
        {% endif %}
    </div>
</div>

<form class="form-inline mb-5">
  <div class="form-group mr-2">
    <input type="text" value="{{ app.request.get('search') }}" class="form-control" name="search" placeholder="Rechercher par titre">
  </div>
  <button type="submit" class="btn btn-primary">Rechercher</button>
</form>


<div class="list-group">
    {% for tvShow in tvShows %}
        <a href="{{ path('tv_show_view', {'id': tvShow.id}) }}" class="list-group-item list-group-item-action">
            {{ tvShow.title }}
        </a>
    {% endfor %}
</div>

{% endblock %}

templates/tv_show/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="d-flex flex-row justify-content-between mb-5">
    <h2>Modifier une série</h2>
    <div>
        <a onClick="return confirm('Confirmez la suppression');" href="{{ path('tv_show_delete', {'id': tvShow.id}) }}" class="btn btn-danger">Supprimer</a>
    </div>
</div>

{{ form_start(tvShowForm) }}
    <div class="row">
        <div class="col-sm-6">
            {{ form_row(tvShowForm.title) }}
            {{ form_row(tvShowForm.releaseDate) }}
            {{ form_row(tvShowForm.directedBy) }}
            {{ form_row(tvShowForm.categories) }}
        </div>
        <div class="col-sm-6">
            {{ form_row(tvShowForm.synopsis) }}
        </div>
    </div>
    <input type="submit" value="Modifier" class="btn btn-primary">
{{ form_end(tvShowForm) }} 

{% endblock %}

templates/tv_show/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="d-flex flex-row justify-content-between">
    <h1>{{ tvShow.title }}</h1>
    <div>
        <a href="{{ path('tv_show_update', {'id': tvShow.id}) }}" class="btn btn-primary">Modifier</a>
    </div>
</div>

<ul class="list-inline">
{% for category in tvShow.categories %}
    <li class="list-inline-item">
        <a href="{{ path('category_view', {'id': category.id}) }}">{{ category.label }}</a>
    </li>
{% endfor %}
</ul>

<p class="jumbotron my-4 p-4">
    {{ tvShow.synopsis }}
</p>

<dl class="row">

  {% if tvShow.directedBy is not empty %}
    <dt class="col-sm-3">Show runner</dt>
    <dd class="col-sm-9">{{ tvShow.directedBy.fullName }}</dd>
  {% endif %}
  {% if tvShow.releaseDate is not empty %}
    <dt class="col-sm-3">Première diffusion</dt>
    <dd class="col-sm-9">{{ tvShow.releaseDate | date("d/m/Y") }}</dd>
  {% endif %}
</dl>

<div class="d-flex flex-row justify-content-between my-4">
    <h2>Personnages principaux</h2>
    <div>
        <a href="{{ path('character_add', {'id': tvShow.id}) }}" class="btn btn-primary">Ajouter</a>
    </div>
</div>

{% for character in tvShow.characters %}
    {% if not loop.first %}
    <hr>
    {% endif %}
    <div class="media">
        {% if character.pictureFilename is not empty %}
            <img src="{{ asset('uploads/' ~ character.pictureFilename) }}" class="mr-3" width="110">
            {% endif %}
        <div class="media-body">
            <h5 class="mt-0">
                {{ character.name }}
                <a href="{{ path('character_update', {'id': character.id}) }}">
                    <i class="far fa-edit"></i>
                </a>
            </h5>
            {% if character.actors is not empty %}
                <ul class="list-inline">
                {% for actor in character.actors %}
                    <li class="list-inline-item">{{ actor.firstName }} {{ actor.lastName }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endfor %}



<div class="d-flex flex-row justify-content-between my-4">
    <h2>Saisons</h2>
    <div>
        <a href="{{ path('season_add', {'id': tvShow.id}) }}" class="btn btn-primary">Ajouter</a>
    </div>
</div>

{% for season in tvShow.seasons %}
    {% if not loop.first %}
        <hr>
    {% endif %}
    <div class="media">
        <div class="media-body">
            <h5 class="mt-0">
                Saison n°{{ season.number }} ({{ season.year }})
                <a href="{{ path('season_update', {'id': season.id}) }}">
                    <i class="far fa-edit"></i>
                </a>
            </h5>
            <ul class="list-unstyled">
            {% for episode in season.episodes %}
                <li>{{ episode.number }} - {{ episode.title }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endfor %}


{% endblock %}